set global local_infile = 1;
CREATE DATABASE IF NOT EXISTS AOC2021;

/* DAY 1 */
DROP TABLE IF EXISTS AOC2021.D1_TEST; CREATE TABLE IF NOT EXISTS AOC2021.D1_TEST(ordering int,RAW_DATA int);
LOAD DATA LOCAL INFILE 'C:\\Users\\Ryan\\Documents\\Git Local\\Advent of Code 2021\\AdventofCode2021\\Test\\SQLRawData\\D1testsql.txt' INTO TABLE AOC2021.D1_TEST
  FIELDS TERMINATED BY ',' ENCLOSED BY '"' LINES TERMINATED BY '\n';
DROP TABLE IF EXISTS AOC2021.D1_INPUT; CREATE TABLE IF NOT EXISTS AOC2021.D1_INPUT(ordering int,RAW_DATA int);
LOAD DATA LOCAL INFILE 'C:\\Users\\Ryan\\Documents\\Git Local\\Advent of Code 2021\\AdventofCode2021\\Test\\SQLRawData\\D1inputsql.txt' INTO TABLE AOC2021.D1_INPUT
  FIELDS TERMINATED BY ',' ENCLOSED BY '"' LINES TERMINATED BY '\n';
  
/* DAY 2 */
DROP TABLE IF EXISTS AOC2021.D2_TEST; CREATE TABLE IF NOT EXISTS AOC2021.D2_TEST(RAW_DATA varchar(10));
LOAD DATA LOCAL INFILE 'C:\\Users\\Ryan\\Documents\\Git Local\\Advent of Code 2021\\AdventofCode2021\\D2\\test.txt' INTO TABLE AOC2021.D2_TEST
  FIELDS TERMINATED BY ',' ENCLOSED BY '"' LINES TERMINATED BY '\n';
DROP TABLE IF EXISTS AOC2021.D2_INPUT; CREATE TABLE IF NOT EXISTS AOC2021.D2_INPUT(RAW_DATA varchar(10));
LOAD DATA LOCAL INFILE 'C:\\Users\\Ryan\\Documents\\Git Local\\Advent of Code 2021\\AdventofCode2021\\D2\\input.txt' INTO TABLE AOC2021.D2_INPUT
  FIELDS TERMINATED BY ',' ENCLOSED BY '"' LINES TERMINATED BY '\n';

/* DAY 3 */
DROP TABLE IF EXISTS AOC2021.D3_TEST; CREATE TABLE IF NOT EXISTS AOC2021.D3_TEST(RAW_DATA varchar(15));
LOAD DATA LOCAL INFILE 'C:\\Users\\Ryan\\Documents\\Git Local\\Advent of Code 2021\\AdventofCode2021\\D3\\test.txt' INTO TABLE AOC2021.D3_TEST
  FIELDS TERMINATED BY ',' ENCLOSED BY '"' LINES TERMINATED BY '\n';
DROP TABLE IF EXISTS AOC2021.D3_INPUT; CREATE TABLE IF NOT EXISTS AOC2021.D3_INPUT(RAW_DATA varchar(15));
LOAD DATA LOCAL INFILE 'C:\\Users\\Ryan\\Documents\\Git Local\\Advent of Code 2021\\AdventofCode2021\\D3\\input.txt' INTO TABLE AOC2021.D3_INPUT
  FIELDS TERMINATED BY ',' ENCLOSED BY '"' LINES TERMINATED BY '\n';
  
  /* DAY 4 */
  /*Have to do some file manipulation becuase formats were weird
DROP TABLE IF EXISTS AOC2021.D4_TEST; CREATE TABLE IF NOT EXISTS AOC2021.D4_TEST(RAW_DATA varchar(15));
LOAD DATA LOCAL INFILE 'C:\\Users\\Ryan\\Documents\\Git Local\\Advent of Code 2021\\AdventofCode2021\\D4\\test.txt' INTO TABLE AOC2021.D4_TEST
  FIELDS TERMINATED BY ',' ENCLOSED BY '"' LINES TERMINATED BY '\n';
DROP TABLE IF EXISTS AOC2021.D4_INPUT; CREATE TABLE IF NOT EXISTS AOC2021.D4_INPUT(RAW_DATA varchar(15));
LOAD DATA LOCAL INFILE 'C:\\Users\\Ryan\\Documents\\Git Local\\Advent of Code 2021\\AdventofCode2021\\D4\\input.txt' INTO TABLE AOC2021.D4_INPUT
  FIELDS TERMINATED BY ',' ENCLOSED BY '"' LINES TERMINATED BY '\n';*/
  
    /* DAY 5 */
DROP TABLE IF EXISTS AOC2021.D5_TEST; CREATE TABLE IF NOT EXISTS AOC2021.D5_TEST(RAW_DATA varchar(25));
LOAD DATA LOCAL INFILE 'C:\\Users\\Ryan\\Documents\\Git Local\\Advent of Code 2021\\AdventofCode2021\\D5\\test.txt' INTO TABLE AOC2021.D5_TEST
  FIELDS TERMINATED BY ',' ENCLOSED BY '"' LINES TERMINATED BY '\n';
DROP TABLE IF EXISTS AOC2021.D5_INPUT; CREATE TABLE IF NOT EXISTS AOC2021.D5_INPUT(RAW_DATA varchar(25));
LOAD DATA LOCAL INFILE 'C:\\Users\\Ryan\\Documents\\Git Local\\Advent of Code 2021\\AdventofCode2021\\D5\\input.txt' INTO TABLE AOC2021.D5_INPUT
  FIELDS TERMINATED BY ',' ENCLOSED BY '"' LINES TERMINATED BY '\n';